'use strict';

// Grande archivio di parole italiane organizzato per categoria, condiviso da
// impiccato, wordle, parola e altri giochi di parole.
// Ogni voce è { word, categoria }. Le parole non contengono spazi e sono in
// MAIUSCOLO (base senza accenti, così il confronto lettera-per-lettera nei
// giochi non risente di accentature). `wordle` usa SOLO le voci di 5 lettere.

const WORD_BANK = [
    // ── Animali ──────────────────────────────────────────────────────────
    { word: 'ELEFANTE', categoria: 'Animali' },
    { word: 'CAVALLO', categoria: 'Animali' },
    { word: 'PIPISTRELLO', categoria: 'Animali' },
    { word: 'PESCE', categoria: 'Animali' },
    { word: 'TIGRE', categoria: 'Animali' },
    { word: 'GATTO', categoria: 'Animali' },
    { word: 'CANE', categoria: 'Animali' },
    { word: 'LEONE', categoria: 'Animali' },
    { word: 'GIRAFFA', categoria: 'Animali' },
    { word: 'ZEBRA', categoria: 'Animali' },
    { word: 'LUPO', categoria: 'Animali' },
    { word: 'VOLPE', categoria: 'Animali' },
    { word: 'ORSO', categoria: 'Animali' },
    { word: 'PANDA', categoria: 'Animali' },
    { word: 'SCIMPANZE', categoria: 'Animali' },
    { word: 'GORILLA', categoria: 'Animali' },
    { word: 'COCCODRILLO', categoria: 'Animali' },
    { word: 'SERPIENTE', categoria: 'Animali' },
    { word: 'RAGNO', categoria: 'Animali' },
    { word: 'FARFALLA', categoria: 'Animali' },
    { word: 'APE', categoria: 'Animali' },
    { word: 'FORMICA', categoria: 'Animali' },
    { word: 'PAPPAGALLO', categoria: 'Animali' },
    { word: 'AQUILA', categoria: 'Animali' },
    { word: 'GUFO', categoria: 'Animali' },
    { word: 'PINGUINO', categoria: 'Animali' },
    { word: 'DELFINO', categoria: 'Animali' },
    { word: 'BALENA', categoria: 'Animali' },
    { word: 'SQUALO', categoria: 'Animali' },
    { word: 'POLPO', categoria: 'Animali' },
    { word: 'CONIGLIO', categoria: 'Animali' },
    { word: 'SCOIATTOLO', categoria: 'Animali' },
    { word: 'RICCIO', categoria: 'Animali' },
    { word: 'TARTARUGA', categoria: 'Animali' },
    { word: 'RANA', categoria: 'Animali' },
    { word: 'CAMALEONTE', categoria: 'Animali' },
    { word: 'ASINO', categoria: 'Animali' },
    { word: 'CERBIATTO', categoria: 'Animali' },
    { word: 'RINOCERONTE', categoria: 'Animali' },
    { word: 'IPPOPOTAMO', categoria: 'Animali' },
    { word: 'CANGURO', categoria: 'Animali' },
    { word: 'KOALA', categoria: 'Animali' },
    { word: 'PULCINO', categoria: 'Animali' },
    { word: 'ANATRA', categoria: 'Animali' },
    { word: 'PICCIONE', categoria: 'Animali' },
    { word: 'CORVO', categoria: 'Animali' },
    { word: 'RONDINE', categoria: 'Animali' },
    { word: 'CICOGNA', categoria: 'Animali' },
    { word: 'FENICOTTERO', categoria: 'Animali' },
    { word: 'TOPO', categoria: 'Animali' },
    { word: 'TALPA', categoria: 'Animali' },
    { word: 'CRICETO', categoria: 'Animali' },
    { word: 'PAVONE', categoria: 'Animali' },
    { word: 'FAGIANO', categoria: 'Animali' },
    { word: 'STRUZZO', categoria: 'Animali' },
    { word: 'CAMMELLO', categoria: 'Animali' },
    { word: 'DROMEDARIO', categoria: 'Animali' },
    { word: 'ALCE', categoria: 'Animali' },
    { word: 'RENNA', categoria: 'Animali' },
    { word: 'SCORPIONE', categoria: 'Animali' },
    { word: 'GIRINO', categoria: 'Animali' },

    // ── Cibo ─────────────────────────────────────────────────────────────
    { word: 'PIZZA', categoria: 'Cibo' },
    { word: 'GELATO', categoria: 'Cibo' },
    { word: 'POMODORO', categoria: 'Cibo' },
    { word: 'CROISSANT', categoria: 'Cibo' },
    { word: 'SPAGHETTI', categoria: 'Cibo' },
    { word: 'LASAGNA', categoria: 'Cibo' },
    { word: 'PASTA', categoria: 'Cibo' },
    { word: 'PANE', categoria: 'Cibo' },
    { word: 'BURRO', categoria: 'Cibo' },
    { word: 'FORMAGGIO', categoria: 'Cibo' },
    { word: 'MOZZARELLA', categoria: 'Cibo' },
    { word: 'SALAME', categoria: 'Cibo' },
    { word: 'PROSCIUTTO', categoria: 'Cibo' },
    { word: 'PANINO', categoria: 'Cibo' },
    { word: 'BRIOCHE', categoria: 'Cibo' },
    { word: 'TORTA', categoria: 'Cibo' },
    { word: 'BISCOTTO', categoria: 'Cibo' },
    { word: 'CIOCCOLATO', categoria: 'Cibo' },
    { word: 'CARAMELLA', categoria: 'Cibo' },
    { word: 'FRUTTA', categoria: 'Cibo' },
    { word: 'MELA', categoria: 'Cibo' },
    { word: 'PERA', categoria: 'Cibo' },
    { word: 'BANANA', categoria: 'Cibo' },
    { word: 'ARANCIA', categoria: 'Cibo' },
    { word: 'LIMONE', categoria: 'Cibo' },
    { word: 'ANGURIA', categoria: 'Cibo' },
    { word: 'PESCA', categoria: 'Cibo' },
    { word: 'UVA', categoria: 'Cibo' },
    { word: 'FICO', categoria: 'Cibo' },
    { word: 'MANDORLA', categoria: 'Cibo' },
    { word: 'NOCCIOLA', categoria: 'Cibo' },
    { word: 'RISOTTO', categoria: 'Cibo' },
    { word: 'MINESTRA', categoria: 'Cibo' },
    { word: 'ZUPPA', categoria: 'Cibo' },
    { word: 'BISTECCA', categoria: 'Cibo' },
    { word: 'POLLO', categoria: 'Cibo' },
    { word: 'TACCHINO', categoria: 'Cibo' },
    { word: 'POLPETTA', categoria: 'Cibo' },
    { word: 'PESTO', categoria: 'Cibo' },
    { word: 'CARBONARA', categoria: 'Cibo' },
    { word: 'AMATRICIANA', categoria: 'Cibo' },
    { word: 'MARMELLATA', categoria: 'Cibo' },
    { word: 'NUTELLA', categoria: 'Cibo' },
    { word: 'MIELE', categoria: 'Cibo' },
    { word: 'CIAMBELLA', categoria: 'Cibo' },
    { word: 'CANNOLO', categoria: 'Cibo' },
    { word: 'TIRAMISU', categoria: 'Cibo' },
    { word: 'PANNA', categoria: 'Cibo' },
    { word: 'YOGURT', categoria: 'Cibo' },
    { word: 'FOCACCIA', categoria: 'Cibo' },
    { word: 'GNOCCHI', categoria: 'Cibo' },
    { word: 'RAVIOLI', categoria: 'Cibo' },
    { word: 'PANETTONE', categoria: 'Cibo' },
    { word: 'PANZEROTTI', categoria: 'Cibo' },
    { word: 'PARMIGIANO', categoria: 'Cibo' },

    // ── Tecnologia ───────────────────────────────────────────────────────
    { word: 'COMPUTER', categoria: 'Tecnologia' },
    { word: 'TELEFONO', categoria: 'Tecnologia' },
    { word: 'ORDINATORE', categoria: 'Tecnologia' },
    { word: 'SMARTPHONE', categoria: 'Tecnologia' },
    { word: 'TABLET', categoria: 'Tecnologia' },
    { word: 'TELECAMERA', categoria: 'Tecnologia' },
    { word: 'ROBOT', categoria: 'Tecnologia' },
    { word: 'INTERNET', categoria: 'Tecnologia' },
    { word: 'CONNESSIONE', categoria: 'Tecnologia' },
    { word: 'WIFI', categoria: 'Tecnologia' },
    { word: 'BATTERIA', categoria: 'Tecnologia' },
    { word: 'CARICATORE', categoria: 'Tecnologia' },
    { word: 'DISPLAY', categoria: 'Tecnologia' },
    { word: 'SCHERMO', categoria: 'Tecnologia' },
    { word: 'TASTIERA', categoria: 'Tecnologia' },
    { word: 'MOUSE', categoria: 'Tecnologia' },
    { word: 'STAMPANTE', categoria: 'Tecnologia' },
    { word: 'SCANNER', categoria: 'Tecnologia' },
    { word: 'ALGORITMO', categoria: 'Tecnologia' },
    { word: 'PROCESSORE', categoria: 'Tecnologia' },
    { word: 'MEMORIA', categoria: 'Tecnologia' },
    { word: 'HARDWARE', categoria: 'Tecnologia' },
    { word: 'SOFTWARE', categoria: 'Tecnologia' },
    { word: 'PROGRAMMA', categoria: 'Tecnologia' },
    { word: 'APPLICAZIONE', categoria: 'Tecnologia' },
    { word: 'VIDEOGIOCO', categoria: 'Tecnologia' },
    { word: 'CONSOLE', categoria: 'Tecnologia' },
    { word: 'DRONE', categoria: 'Tecnologia' },
    { word: 'FOTOCAMERA', categoria: 'Tecnologia' },
    { word: 'CASCHETTE', categoria: 'Tecnologia' },
    { word: 'CUFFIE', categoria: 'Tecnologia' },
    { word: 'SERVER', categoria: 'Tecnologia' },
    { word: 'CLOUD', categoria: 'Tecnologia' },
    { word: 'MICROPROCESSORE', categoria: 'Tecnologia' },
    { word: 'PORTAVOZ', categoria: 'Tecnologia' },
    { word: 'CABLO', categoria: 'Tecnologia' },
    { word: 'DATI', categoria: 'Tecnologia' },
    { word: 'CODICE', categoria: 'Tecnologia' },
    { word: 'VIRUS', categoria: 'Tecnologia' },
    { word: 'ANTIVIRUS', categoria: 'Tecnologia' },

    // ── Natura ───────────────────────────────────────────────────────────
    { word: 'GIUNGLA', categoria: 'Natura' },
    { word: 'ARCOBALENO', categoria: 'Natura' },
    { word: 'FIORE', categoria: 'Natura' },
    { word: 'ROSA', categoria: 'Natura' },
    { word: 'MARGHERITA', categoria: 'Natura' },
    { word: 'TULIPANO', categoria: 'Natura' },
    { word: 'GIRASOLE', categoria: 'Natura' },
    { word: 'ALBERO', categoria: 'Natura' },
    { word: 'QUERCIA', categoria: 'Natura' },
    { word: 'PINO', categoria: 'Natura' },
    { word: 'FOGLIA', categoria: 'Natura' },
    { word: 'RADICE', categoria: 'Natura' },
    { word: 'FIUME', categoria: 'Natura' },
    { word: 'LAGO', categoria: 'Natura' },
    { word: 'MARE', categoria: 'Natura' },
    { word: 'COLLINA', categoria: 'Natura' },
    { word: 'VALLE', categoria: 'Natura' },
    { word: 'ERUZIONE', categoria: 'Natura' },
    { word: 'TERREMOTO', categoria: 'Natura' },
    { word: 'TEMPESTA', categoria: 'Natura' },
    { word: 'TORNADO', categoria: 'Natura' },
    { word: 'FRANA', categoria: 'Natura' },
    { word: 'CAMPO', categoria: 'Natura' },
    { word: 'PRATO', categoria: 'Natura' },
    { word: 'BOSCO', categoria: 'Natura' },
    { word: 'OASI', categoria: 'Natura' },
    { word: 'GHIACCIAIO', categoria: 'Natura' },
    { word: 'CASCATA', categoria: 'Natura' },
    { word: 'NEVE', categoria: 'Natura' },
    { word: 'PIOGGIA', categoria: 'Natura' },
    { word: 'GRANDINE', categoria: 'Natura' },
    { word: 'NUVOLA', categoria: 'Natura' },
    { word: 'VENTO', categoria: 'Natura' },
    { word: 'TERRA', categoria: 'Natura' },
    { word: 'STAGIONE', categoria: 'Natura' },
    { word: 'FORESTA', categoria: 'Natura' },
    { word: 'RUSCELLO', categoria: 'Natura' },
    { word: 'SCATOLA', categoria: 'Natura' },
    { word: 'FUOCO', categoria: 'Natura' },

    // ── Spazio ───────────────────────────────────────────────────────────
    { word: 'STELLA', categoria: 'Spazio' },
    { word: 'SOLE', categoria: 'Spazio' },
    { word: 'LUNA', categoria: 'Spazio' },
    { word: 'MARTE', categoria: 'Spazio' },
    { word: 'GIOVE', categoria: 'Spazio' },
    { word: 'SATURNO', categoria: 'Spazio' },
    { word: 'URANO', categoria: 'Spazio' },
    { word: 'NETTUNO', categoria: 'Spazio' },
    { word: 'MERCURIO', categoria: 'Spazio' },
    { word: 'VENERE', categoria: 'Spazio' },
    { word: 'PLUTONE', categoria: 'Spazio' },
    { word: 'GALASSIA', categoria: 'Spazio' },
    { word: 'COMETA', categoria: 'Spazio' },
    { word: 'ASTEROIDE', categoria: 'Spazio' },
    { word: 'METEORA', categoria: 'Spazio' },
    { word: 'PIANETA', categoria: 'Spazio' },
    { word: 'ORBITA', categoria: 'Spazio' },
    { word: 'GRAVITA', categoria: 'Spazio' },
    { word: 'ECLISSI', categoria: 'Spazio' },
    { word: 'COSMO', categoria: 'Spazio' },
    { word: 'UNIVERSO', categoria: 'Spazio' },
    { word: 'TELESCOPIO', categoria: 'Spazio' },
    { word: 'NALBERGHI', categoria: 'Spazio' },
    { word: 'SUPERNOVA', categoria: 'Spazio' },
    { word: 'COSTELLAZIONE', categoria: 'Spazio' },
    { word: 'NEBULOSA', categoria: 'Spazio' },

    // ── Geografia ────────────────────────────────────────────────────────
    { word: 'SAHARA', categoria: 'Geografia' },
    { word: 'AMAZZONIA', categoria: 'Geografia' },
    { word: 'EQUATORE', categoria: 'Geografia' },
    { word: 'CONTINENTE', categoria: 'Geografia' },
    { word: 'CAPITALE', categoria: 'Geografia' },
    { word: 'CONFINE', categoria: 'Geografia' },
    { word: 'ISOLA', categoria: 'Geografia' },
    { word: 'PENISOLA', categoria: 'Geografia' },
    { word: 'ARCIPELAGO', categoria: 'Geografia' },
    { word: 'COSTA', categoria: 'Geografia' },
    { word: 'PORTO', categoria: 'Geografia' },
    { word: 'CANALE', categoria: 'Geografia' },
    { word: 'PLANURA', categoria: 'Geografia' },
    { word: 'ALTIPIANO', categoria: 'Geografia' },
    { word: 'ESPOSIZIONE', categoria: 'Geografia' },

    // ── Luoghi ───────────────────────────────────────────────────────────
    { word: 'BIBLIOTECA', categoria: 'Luoghi' },
    { word: 'CASTELLO', categoria: 'Luoghi' },
    { word: 'OSPEDALE', categoria: 'Luoghi' },
    { word: 'STADIO', categoria: 'Luoghi' },
    { word: 'TEATRO', categoria: 'Luoghi' },
    { word: 'CINEMA', categoria: 'Luoghi' },
    { word: 'MUSEO', categoria: 'Luoghi' },
    { word: 'CHIESA', categoria: 'Luoghi' },
    { word: 'MERCATO', categoria: 'Luoghi' },
    { word: 'SUPERMERCATO', categoria: 'Luoghi' },
    { word: 'FARMACIA', categoria: 'Luoghi' },
    { word: 'POLIZIA', categoria: 'Luoghi' },
    { word: 'CASERMA', categoria: 'Luoghi' },
    { word: 'SCUOLA', categoria: 'Luoghi' },
    { word: 'UNIVERSITA', categoria: 'Luoghi' },
    { word: 'GIARDINO', categoria: 'Luoghi' },
    { word: 'PARCHEGGIO', categoria: 'Luoghi' },
    { word: 'CARCERE', categoria: 'Luoghi' },
    { word: 'RESTAURANTE', categoria: 'Luoghi' },
    { word: 'BANCA', categoria: 'Luoghi' },

    // ── Mestieri ─────────────────────────────────────────────────────────
    { word: 'ASTRONAUTA', categoria: 'Mestieri' },
    { word: 'DENTISTA', categoria: 'Mestieri' },
    { word: 'MAESTRA', categoria: 'Mestieri' },
    { word: 'POETA', categoria: 'Mestieri' },
    { word: 'PITTORE', categoria: 'Mestieri' },
    { word: 'SCULTORE', categoria: 'Mestieri' },
    { word: 'MURATORE', categoria: 'Mestieri' },
    { word: 'IDRAULICO', categoria: 'Mestieri' },
    { word: 'ELETTRICISTA', categoria: 'Mestieri' },
    { word: 'CUOCO', categoria: 'Mestieri' },
    { word: 'PASTICCIERE', categoria: 'Mestieri' },
    { word: 'FORNAIO', categoria: 'Mestieri' },
    { word: 'IMPIEGATO', categoria: 'Mestieri' },
    { word: 'DIRETTORE', categoria: 'Mestieri' },
    { word: 'GIORNALISTA', categoria: 'Mestieri' },
    { word: 'SCRITTORE', categoria: 'Mestieri' },
    { word: 'MUSICISTA', categoria: 'Mestieri' },
    { word: 'CANTANTE', categoria: 'Mestieri' },
    { word: 'BALLERINA', categoria: 'Mestieri' },
    { word: 'ATTORE', categoria: 'Mestieri' },
    { word: 'MAGO', categoria: 'Mestieri' },
    { word: 'VETERINARIO', categoria: 'Mestieri' },
    { word: 'ARCHITETTO', categoria: 'Mestieri' },
    { word: 'INGEGNERE', categoria: 'Mestieri' },
    { word: 'AVVOCATO', categoria: 'Mestieri' },
    { word: 'GIUDICE', categoria: 'Mestieri' },
    { word: 'POLIZIOTTO', categoria: 'Mestieri' },
    { word: 'VIGILE', categoria: 'Mestieri' },
    { word: 'MECCANICO', categoria: 'Mestieri' },
    { word: 'FALEGNAME', categoria: 'Mestieri' },
    { word: 'SARTORE', categoria: 'Mestieri' },
    { word: 'CALZOLAIO', categoria: 'Mestieri' },

    // ── Musica ───────────────────────────────────────────────────────────
    { word: 'CHITARRA', categoria: 'Musica' },
    { word: 'PIANOFORTE', categoria: 'Musica' },
    { word: 'VIOLINO', categoria: 'Musica' },
    { word: 'VIOLONCELLO', categoria: 'Musica' },
    { word: 'FLAUTO', categoria: 'Musica' },
    { word: 'TRUMPET', categoria: 'Musica' },
    { word: 'TROMBA', categoria: 'Musica' },
    { word: 'SASSOFONO', categoria: 'Musica' },
    { word: 'BATTERIA', categoria: 'Musica' },
    { word: 'CAMPANELLA', categoria: 'Musica' },
    { word: 'OPERA', categoria: 'Musica' },
    { word: 'SINFONIA', categoria: 'Musica' },
    { word: 'SPARTITO', categoria: 'Musica' },
    { word: 'NOTE', categoria: 'Musica' },
    { word: 'ACCORDO', categoria: 'Musica' },
    { word: 'MELODIA', categoria: 'Musica' },
    { word: 'RITMO', categoria: 'Musica' },
    { word: 'CONCERTO', categoria: 'Musica' },
    { word: 'RADIO', categoria: 'Musica' },
    { word: 'CANTANTE', categoria: 'Musica' },

    // ── Sport ────────────────────────────────────────────────────────────
    { word: 'BICICLETTA', categoria: 'Sport' },
    { word: 'CAMPIONE', categoria: 'Sport' },
    { word: 'CALCIO', categoria: 'Sport' },
    { word: 'PALLONE', categoria: 'Sport' },
    { word: 'PORTIERE', categoria: 'Sport' },
    { word: 'ALLENATORE', categoria: 'Sport' },
    { word: 'MARATONA', categoria: 'Sport' },
    { word: 'ATLETICA', categoria: 'Sport' },
    { word: 'NUOTO', categoria: 'Sport' },
    { word: 'PISCINA', categoria: 'Sport' },
    { word: 'SCI', categoria: 'Sport' },
    { word: 'SNOWBOARD', categoria: 'Sport' },
    { word: 'TENNIS', categoria: 'Sport' },
    { word: 'RACCHETTA', categoria: 'Sport' },
    { word: 'PALLACANESTRO', categoria: 'Sport' },
    { word: 'PALLANUOTO', categoria: 'Sport' },
    { word: 'CICLISMO', categoria: 'Sport' },
    { word: 'SCACCHI', categoria: 'Sport' },
    { word: 'PUGILATO', categoria: 'Sport' },
    { word: 'GINNASTICA', categoria: 'Sport' },
    { word: 'VOLLEY', categoria: 'Sport' },
    { word: 'RUGBY', categoria: 'Sport' },
    { word: 'AEROBICA', categoria: 'Sport' },
    { word: 'PATTINAGGIO', categoria: 'Sport' },

    // ── Auto ─────────────────────────────────────────────────────────────
    { word: 'FERRARI', categoria: 'Auto' },
    { word: 'LAMBORGHINI', categoria: 'Auto' },
    { word: 'MASERATI', categoria: 'Auto' },
    { word: 'VOLANTE', categoria: 'Auto' },
    { word: 'MOTORE', categoria: 'Auto' },
    { word: 'FRENO', categoria: 'Auto' },
    { word: 'CAMBIO', categoria: 'Auto' },
    { word: 'FANALE', categoria: 'Auto' },
    { word: 'PARAFANGHI', categoria: 'Auto' },
    { word: 'GARAGE', categoria: 'Auto' },
    { word: 'RUOTE', categoria: 'Auto' },
    { word: 'PATENTE', categoria: 'Auto' },
    { word: 'SEMAFORO', categoria: 'Auto' },
    { word: 'AUTOSTRADA', categoria: 'Auto' },

    // ── Mezzi ────────────────────────────────────────────────────────────
    { word: 'TRENO', categoria: 'Mezzi' },
    { word: 'BARCA', categoria: 'Mezzi' },
    { word: 'AEREO', categoria: 'Mezzi' },
    { word: 'AUTOBUS', categoria: 'Mezzi' },
    { word: 'METROPOLITANA', categoria: 'Mezzi' },
    { word: 'TRAM', categoria: 'Mezzi' },
    { word: 'NAVE', categoria: 'Mezzi' },
    { word: 'SOMMERGIBILE', categoria: 'Mezzi' },
    { word: 'ELICOTTERO', categoria: 'Mezzi' },
    { word: 'MONOPATTINO', categoria: 'Mezzi' },
    { word: 'TAXI', categoria: 'Mezzi' },
    { word: 'CAMION', categoria: 'Mezzi' },
    { word: 'FURGONE', categoria: 'Mezzi' },

    // ── Mitologia ────────────────────────────────────────────────────────
    { word: 'DRAGO', categoria: 'Mitologia' },
    { word: 'MUMIA', categoria: 'Mitologia' },
    { word: 'FENICE', categoria: 'Mitologia' },
    { word: 'UNICORNO', categoria: 'Mitologia' },
    { word: 'PEGASO', categoria: 'Mitologia' },
    { word: 'CENTAURO', categoria: 'Mitologia' },
    { word: 'MINOTAURO', categoria: 'Mitologia' },
    { word: 'SIRENA', categoria: 'Mitologia' },
    { word: 'MEDUSA', categoria: 'Mitologia' },
    { word: 'ZEUS', categoria: 'Mitologia' },
    { word: 'ATENA', categoria: 'Mitologia' },
    { word: 'ERCOLE', categoria: 'Mitologia' },
    { word: 'ABISSO', categoria: 'Mitologia' },
    { word: 'SIRENA', categoria: 'Mitologia' },
    { word: 'FENICE', categoria: 'Mitologia' },
    { word: 'OLIMPO', categoria: 'Mitologia' },
    { word: 'EREMITA', categoria: 'Mitologia' },

    // ── Altro ────────────────────────────────────────────────────────────
    { word: 'FANTASMA', categoria: 'Altro' },
    { word: 'VAMPIRONE', categoria: 'Altro' },
    { word: 'ZOMBIE', categoria: 'Altro' },
    { word: 'BEFANA', categoria: 'Altro' },
    { word: 'STREGA', categoria: 'Altro' },
    { word: 'FATA', categoria: 'Altro' },
    { word: 'MISTERIO', categoria: 'Altro' },
    { word: 'SEGRETO', categoria: 'Altro' },
    { word: 'AVVENTURA', categoria: 'Altro' },
    { word: 'VIAGGIO', categoria: 'Altro' },
    { word: 'VACANZA', categoria: 'Altro' },
    { word: 'FESTA', categoria: 'Altro' },
    { word: 'COMPLEANNO', categoria: 'Altro' },
    { word: 'MATRIMONIO', categoria: 'Altro' },
    { word: 'REGGALO', categoria: 'Altro' },
    { word: 'SORPRESA', categoria: 'Altro' },
    { word: 'FORZA', categoria: 'Altro' },
    { word: 'CORAGGIO', categoria: 'Altro' },
    { word: 'AMICIZIA', categoria: 'Altro' },
    { word: 'PERICOLO', categoria: 'Altro' },
    { word: 'GIOIA', categoria: 'Altro' },
    { word: 'TRISTEZZA', categoria: 'Altro' },
    { word: 'PAURA', categoria: 'Altro' },
    { word: 'RABBIA', categoria: 'Altro' },
    { word: 'PAZIENTE', categoria: 'Altro' },
    { word: 'RICCHEZZA', categoria: 'Altro' },
    { word: 'GENEROSITA', categoria: 'Altro' },
    { word: 'PATRON', categoria: 'Altro' },
    { word: 'PREMIERA', categoria: 'Altro' },

    // ── Personaggi ───────────────────────────────────────────────────────
    { word: 'PINOCCHIO', categoria: 'Personaggi' },
    { word: 'CENERENTOLA', categoria: 'Personaggi' },
    { word: 'BIANCANEVE', categoria: 'Personaggi' },
    { word: 'MARIO', categoria: 'Personaggi' },
    { word: 'LUIGI', categoria: 'Personaggi' },
    { word: 'SHREK', categoria: 'Personaggi' },
    { word: 'BATMAN', categoria: 'Personaggi' },
    { word: 'HULK', categoria: 'Personaggi' },
    { word: 'THOR', categoria: 'Personaggi' },
    { word: 'WONDERWOMAN', categoria: 'Personaggi' },
    { word: 'SUPERMAN', categoria: 'Personaggi' },
    { word: 'SPIDERMAN', categoria: 'Personaggi' },
    { word: 'IRONMAN', categoria: 'Personaggi' },
    { word: 'PIPPO', categoria: 'Personaggi' },
    { word: 'PLUTO', categoria: 'Personaggi' },
    { word: 'TOPOLINO', categoria: 'Personaggi' },
    { word: 'PAPERINO', categoria: 'Personaggi' },
    { word: 'ZORRO', categoria: 'Personaggi' },
    { word: 'TARZAN', categoria: 'Personaggi' },
    { word: 'ROBINHOOD', categoria: 'Personaggi' },
    { word: 'GULLIVER', categoria: 'Personaggi' },
    { word: 'POCAHONTAS', categoria: 'Personaggi' },
    { word: 'ALADINO', categoria: 'Personaggi' },
    { word: 'SINDBAD', categoria: 'Personaggi' },
];

// Normalizza una parola per confronti: MAIUSCOLO, niente spazi/segni.
const norm = (w) => String(w || '').toUpperCase().replace(/[^A-Z]/g, '');

// Sotto-archivio utile per il Wordle: solo parole di 5 lettere "pulite"
// (5 caratteri MAIUSCOLI senza accenti), senza duplicati. Così la parola
// mostrata e quella da digitare coincidono sempre.
const WORDLE_POOL = Array.from(
    new Map(WORD_BANK
        .filter((w) => /^[A-Z]{5}$/.test(w.word))
        .map((w) => [w.word, w]))
        .values()
);

// Filtra per lunghezza (in lettere normalizzate), es. { minLen, maxLen }.
const filterByLen = (minLen, maxLen) =>
    WORD_BANK.filter((w) => {
        const len = norm(w.word).length;
        return len >= minLen && len <= maxLen;
    });

// Seleziona una parola escludendo quelle già usate, così niente ripetizioni
// finché non si esaurisce l'archivio (poi riparte).
// Ritorna { word, categoria, used } dove `used` è il nuovo elenco aggiornato.
const pickWord = ({ minLen = 1, maxLen = 99, exclude = [], random = Math.random } = {}) => {
    const pool = filterByLen(minLen, maxLen);
    const fresh = pool.filter((w) => !exclude.includes(norm(w.word)));
    const candidates = fresh.length ? fresh : pool;
    const entry = candidates[Math.floor(random() * candidates.length)];
    const word = norm(entry.word);
    return { word, categoria: entry.categoria, used: [...exclude, word] };
};

module.exports = {
    WORD_BANK,
    WORDLE_POOL,
    norm,
    filterByLen,
    pickWord,
};