'use strict';

// Grande archivio di parole italiane organizzato per categoria, condiviso da
// impiccato, wordle, parola e altri giochi di parole.
// Ogni voce è { word, categoria }. Le parole non contengono spazi e sono in
// MAIUSCOLO (base senza accenti, così il confronto lettera-per-lettera nei
// giochi non risente di accentature). `wordle` usa SOLO le voci di 5 lettere.

const WORD_BANK = [
    // ── Animali ──────────────────────────────────────────────────────────
    { word: 'ELEFANTE', categoria: 'Animali' },
    { word: 'CAVALLO', categoria: 'Animali' },
    { word: 'PIPISTRELLO', categoria: 'Animali' },
    { word: 'PESCE', categoria: 'Animali' },
    { word: 'TIGRE', categoria: 'Animali' },
    { word: 'GATTO', categoria: 'Animali' },
    { word: 'CANE', categoria: 'Animali' },
    { word: 'LEONE', categoria: 'Animali' },
    { word: 'GIRAFFA', categoria: 'Animali' },
    { word: 'ZEBRA', categoria: 'Animali' },
    { word: 'LUPO', categoria: 'Animali' },
    { word: 'VOLPE', categoria: 'Animali' },
    { word: 'ORSO', categoria: 'Animali' },
    { word: 'PANDA', categoria: 'Animali' },
    { word: 'SCIMPANZE', categoria: 'Animali' },
    { word: 'GORILLA', categoria: 'Animali' },
    { word: 'COCCODRILLO', categoria: 'Animali' },
    { word: 'SERPIENTE', categoria: 'Animali' },
    { word: 'RAGNO', categoria: 'Animali' },
    { word: 'FARFALLA', categoria: 'Animali' },
    { word: 'APE', categoria: 'Animali' },
    { word: 'FORMICA', categoria: 'Animali' },
    { word: 'PAPPAGALLO', categoria: 'Animali' },
    { word: 'AQUILA', categoria: 'Animali' },
    { word: 'GUFO', categoria: 'Animali' },
    { word: 'PINGUINO', categoria: 'Animali' },
    { word: 'DELFINO', categoria: 'Animali' },
    { word: 'BALENA', categoria: 'Animali' },
    { word: 'SQUALO', categoria: 'Animali' },
    { word: 'POLPO', categoria: 'Animali' },
    { word: 'CONIGLIO', categoria: 'Animali' },
    { word: 'SCOIATTOLO', categoria: 'Animali' },
    { word: 'RICCIO', categoria: 'Animali' },
    { word: 'TARTARUGA', categoria: 'Animali' },
    { word: 'RANA', categoria: 'Animali' },
    { word: 'CAMALEONTE', categoria: 'Animali' },
    { word: 'ASINO', categoria: 'Animali' },
    { word: 'CERBIATTO', categoria: 'Animali' },
    { word: 'RINOCERONTE', categoria: 'Animali' },
    { word: 'IPPOPOTAMO', categoria: 'Animali' },
    { word: 'CANGURO', categoria: 'Animali' },
    { word: 'KOALA', categoria: 'Animali' },
    { word: 'PULCINO', categoria: 'Animali' },
    { word: 'ANATRA', categoria: 'Animali' },
    { word: 'PICCIONE', categoria: 'Animali' },
    { word: 'CORVO', categoria: 'Animali' },
    { word: 'RONDINE', categoria: 'Animali' },
    { word: 'CICOGNA', categoria: 'Animali' },
    { word: 'FENICOTTERO', categoria: 'Animali' },
    { word: 'TOPO', categoria: 'Animali' },
    { word: 'TALPA', categoria: 'Animali' },
    { word: 'CRICETO', categoria: 'Animali' },
    { word: 'PAVONE', categoria: 'Animali' },
    { word: 'FAGIANO', categoria: 'Animali' },
    { word: 'STRUZZO', categoria: 'Animali' },
    { word: 'CAMMELLO', categoria: 'Animali' },
    { word: 'DROMEDARIO', categoria: 'Animali' },
    { word: 'ALCE', categoria: 'Animali' },
    { word: 'RENNA', categoria: 'Animali' },
    { word: 'SCORPIONE', categoria: 'Animali' },
    { word: 'GIRINO', categoria: 'Animali' },

    // ── Cibo ─────────────────────────────────────────────────────────────
    { word: 'PIZZA', categoria: 'Cibo' },
    { word: 'GELATO', categoria: 'Cibo' },
    { word: 'POMODORO', categoria: 'Cibo' },
    { word: 'CROISSANT', categoria: 'Cibo' },
    { word: 'SPAGHETTI', categoria: 'Cibo' },
    { word: 'LASAGNA', categoria: 'Cibo' },
    { word: 'PASTA', categoria: 'Cibo' },
    { word: 'PANE', categoria: 'Cibo' },
    { word: 'BURRO', categoria: 'Cibo' },
    { word: 'FORMAGGIO', categoria: 'Cibo' },
    { word: 'MOZZARELLA', categoria: 'Cibo' },
    { word: 'SALAME', categoria: 'Cibo' },
    { word: 'PROSCIUTTO', categoria: 'Cibo' },
    { word: 'PANINO', categoria: 'Cibo' },
    { word: 'BRIOCHE', categoria: 'Cibo' },
    { word: 'TORTA', categoria: 'Cibo' },
    { word: 'BISCOTTO', categoria: 'Cibo' },
    { word: 'CIOCCOLATO', categoria: 'Cibo' },
    { word: 'CARAMELLA', categoria: 'Cibo' },
    { word: 'FRUTTA', categoria: 'Cibo' },
    { word: 'MELA', categoria: 'Cibo' },
    { word: 'PERA', categoria: 'Cibo' },
    { word: 'BANANA', categoria: 'Cibo' },
    { word: 'ARANCIA', categoria: 'Cibo' },
    { word: 'LIMONE', categoria: 'Cibo' },
    { word: 'ANGURIA', categoria: 'Cibo' },
    { word: 'PESCA', categoria: 'Cibo' },
    { word: 'UVA', categoria: 'Cibo' },
    { word: 'FICO', categoria: 'Cibo' },
    { word: 'MANDORLA', categoria: 'Cibo' },
    { word: 'NOCCIOLA', categoria: 'Cibo' },
    { word: 'RISOTTO', categoria: 'Cibo' },
    { word: 'MINESTRA', categoria: 'Cibo' },
    { word: 'ZUPPA', categoria: 'Cibo' },
    { word: 'BISTECCA', categoria: 'Cibo' },
    { word: 'POLLO', categoria: 'Cibo' },
    { word: 'TACCHINO', categoria: 'Cibo' },
    { word: 'POLPETTA', categoria: 'Cibo' },
    { word: 'PESTO', categoria: 'Cibo' },
    { word: 'CARBONARA', categoria: 'Cibo' },
    { word: 'AMATRICIANA', categoria: 'Cibo' },
    { word: 'MARMELLATA', categoria: 'Cibo' },
    { word: 'NUTELLA', categoria: 'Cibo' },
    { word: 'MIELE', categoria: 'Cibo' },
    { word: 'CIAMBELLA', categoria: 'Cibo' },
    { word: 'CANNOLO', categoria: 'Cibo' },
    { word: 'TIRAMISU', categoria: 'Cibo' },
    { word: 'PANNA', categoria: 'Cibo' },
    { word: 'YOGURT', categoria: 'Cibo' },
    { word: 'FOCACCIA', categoria: 'Cibo' },
    { word: 'GNOCCHI', categoria: 'Cibo' },
    { word: 'RAVIOLI', categoria: 'Cibo' },
    { word: 'PANETTONE', categoria: 'Cibo' },
    { word: 'PANZEROTTI', categoria: 'Cibo' },
    { word: 'PARMIGIANO', categoria: 'Cibo' },

    // ── Tecnologia ───────────────────────────────────────────────────────
    { word: 'COMPUTER', categoria: 'Tecnologia' },
    { word: 'TELEFONO', categoria: 'Tecnologia' },
    { word: 'ORDINATORE', categoria: 'Tecnologia' },
    { word: 'SMARTPHONE', categoria: 'Tecnologia' },
    { word: 'TABLET', categoria: 'Tecnologia' },
    { word: 'TELECAMERA', categoria: 'Tecnologia' },
    { word: 'ROBOT', categoria: 'Tecnologia' },
    { word: 'INTERNET', categoria: 'Tecnologia' },
    { word: 'CONNESSIONE', categoria: 'Tecnologia' },
    { word: 'WIFI', categoria: 'Tecnologia' },
    { word: 'BATTERIA', categoria: 'Tecnologia' },
    { word: 'CARICATORE', categoria: 'Tecnologia' },
    { word: 'DISPLAY', categoria: 'Tecnologia' },
    { word: 'SCHERMO', categoria: 'Tecnologia' },
    { word: 'TASTIERA', categoria: 'Tecnologia' },
    { word: 'MOUSE', categoria: 'Tecnologia' },
    { word: 'STAMPANTE', categoria: 'Tecnologia' },
    { word: 'SCANNER', categoria: 'Tecnologia' },
    { word: 'ALGORITMO', categoria: 'Tecnologia' },
    { word: 'PROCESSORE', categoria: 'Tecnologia' },
    { word: 'MEMORIA', categoria: 'Tecnologia' },
    { word: 'HARDWARE', categoria: 'Tecnologia' },
    { word: 'SOFTWARE', categoria: 'Tecnologia' },
    { word: 'PROGRAMMA', categoria: 'Tecnologia' },
    { word: 'APPLICAZIONE', categoria: 'Tecnologia' },
    { word: 'VIDEOGIOCO', categoria: 'Tecnologia' },
    { word: 'CONSOLE', categoria: 'Tecnologia' },
    { word: 'DRONE', categoria: 'Tecnologia' },
    { word: 'FOTOCAMERA', categoria: 'Tecnologia' },
    { word: 'CASCHETTE', categoria: 'Tecnologia' },
    { word: 'CUFFIE', categoria: 'Tecnologia' },
    { word: 'SERVER', categoria: 'Tecnologia' },
    { word: 'CLOUD', categoria: 'Tecnologia' },
    { word: 'MICROPROCESSORE', categoria: 'Tecnologia' },
    { word: 'DATA', categoria: 'Tecnologia' },
    { word: 'DATI', categoria: 'Tecnologia' },
    { word: 'CODICE', categoria: 'Tecnologia' },
    { word: 'VIRUS', categoria: 'Tecnologia' },
    { word: 'ANTIVIRUS', categoria: 'Tecnologia' },

    // ── Natura ───────────────────────────────────────────────────────────
    { word: 'GIUNGLA', categoria: 'Natura' },
    { word: 'ARCOBALENO', categoria: 'Natura' },
    { word: 'FIORE', categoria: 'Natura' },
    { word: 'ROSA', categoria: 'Natura' },
    { word: 'MARGHERITA', categoria: 'Natura' },
    { word: 'TULIPANO', categoria: 'Natura' },
    { word: 'GIRASOLE', categoria: 'Natura' },
    { word: 'ALBERO', categoria: 'Natura' },
    { word: 'QUERCIA', categoria: 'Natura' },
    { word: 'PINO', categoria: 'Natura' },
    { word: 'FOGLIA', categoria: 'Natura' },
    { word: 'RADICE', categoria: 'Natura' },
    { word: 'FIUME', categoria: 'Natura' },
    { word: 'LAGO', categoria: 'Natura' },
    { word: 'MARE', categoria: 'Natura' },
    { word: 'COLLINA', categoria: 'Natura' },
    { word: 'VALLE', categoria: 'Natura' },
    { word: 'ERUZIONE', categoria: 'Natura' },
    { word: 'TERREMOTO', categoria: 'Natura' },
    { word: 'TEMPESTA', categoria: 'Natura' },
    { word: 'TORNADO', categoria: 'Natura' },
    { word: 'FRANA', categoria: 'Natura' },
    { word: 'CAMPO', categoria: 'Natura' },
    { word: 'PRATO', categoria: 'Natura' },
    { word: 'BOSCO', categoria: 'Natura' },
    { word: 'OASI', categoria: 'Natura' },
    { word: 'GHIACCIAIO', categoria: 'Natura' },
    { word: 'CASCATA', categoria: 'Natura' },
    { word: 'NEVE', categoria: 'Natura' },
    { word: 'PIOGGIA', categoria: 'Natura' },
    { word: 'GRANDINE', categoria: 'Natura' },
    { word: 'NUVOLA', categoria: 'Natura' },
    { word: 'VENTO', categoria: 'Natura' },
    { word: 'TERRA', categoria: 'Natura' },
    { word: 'STAGIONE', categoria: 'Natura' },
    { word: 'FORESTA', categoria: 'Natura' },
    { word: 'RUSCELLO', categoria: 'Natura' },
    { word: 'FUOCO', categoria: 'Natura' },

    // ── Spazio ───────────────────────────────────────────────────────────
    { word: 'STELLA', categoria: 'Spazio' },
    { word: 'SOLE', categoria: 'Spazio' },
    { word: 'LUNA', categoria: 'Spazio' },
    { word: 'MARTE', categoria: 'Spazio' },
    { word: 'GIOVE', categoria: 'Spazio' },
    { word: 'SATURNO', categoria: 'Spazio' },
    { word: 'URANO', categoria: 'Spazio' },
    { word: 'NETTUNO', categoria: 'Spazio' },
    { word: 'MERCURIO', categoria: 'Spazio' },
    { word: 'VENERE', categoria: 'Spazio' },
    { word: 'PLUTONE', categoria: 'Spazio' },
    { word: 'GALASSIA', categoria: 'Spazio' },
    { word: 'COMETA', categoria: 'Spazio' },
    { word: 'ASTEROIDE', categoria: 'Spazio' },
    { word: 'METEORA', categoria: 'Spazio' },
    { word: 'PIANETA', categoria: 'Spazio' },
    { word: 'ORBITA', categoria: 'Spazio' },
    { word: 'GRAVITA', categoria: 'Spazio' },
    { word: 'ECLISSI', categoria: 'Spazio' },
    { word: 'COSMO', categoria: 'Spazio' },
    { word: 'UNIVERSO', categoria: 'Spazio' },
    { word: 'TELESCOPIO', categoria: 'Spazio' },
    { word: 'SUPERNOVA', categoria: 'Spazio' },
    { word: 'COSTELLAZIONE', categoria: 'Spazio' },
    { word: 'NEBULOSA', categoria: 'Spazio' },

    // ── Geografia ────────────────────────────────────────────────────────
    { word: 'SAHARA', categoria: 'Geografia' },
    { word: 'AMAZZONIA', categoria: 'Geografia' },
    { word: 'EQUATORE', categoria: 'Geografia' },
    { word: 'CONTINENTE', categoria: 'Geografia' },
    { word: 'CAPITALE', categoria: 'Geografia' },
    { word: 'CONFINE', categoria: 'Geografia' },
    { word: 'ISOLA', categoria: 'Geografia' },
    { word: 'PENISOLA', categoria: 'Geografia' },
    { word: 'ARCIPELAGO', categoria: 'Geografia' },
    { word: 'COSTA', categoria: 'Geografia' },
    { word: 'PORTO', categoria: 'Geografia' },
    { word: 'CANALE', categoria: 'Geografia' },
    { word: 'PLANURA', categoria: 'Geografia' },
    { word: 'ALTIPIANO', categoria: 'Geografia' },

    // ── Luoghi ───────────────────────────────────────────────────────────
    { word: 'BIBLIOTECA', categoria: 'Luoghi' },
    { word: 'CASTELLO', categoria: 'Luoghi' },
    { word: 'OSPEDALE', categoria: 'Luoghi' },
    { word: 'STADIO', categoria: 'Luoghi' },
    { word: 'TEATRO', categoria: 'Luoghi' },
    { word: 'CINEMA', categoria: 'Luoghi' },
    { word: 'MUSEO', categoria: 'Luoghi' },
    { word: 'CHIESA', categoria: 'Luoghi' },
    { word: 'MERCATO', categoria: 'Luoghi' },
    { word: 'SUPERMERCATO', categoria: 'Luoghi' },
    { word: 'FARMACIA', categoria: 'Luoghi' },
    { word: 'POLIZIA', categoria: 'Luoghi' },
    { word: 'CASERMA', categoria: 'Luoghi' },
    { word: 'SCUOLA', categoria: 'Luoghi' },
    { word: 'UNIVERSITA', categoria: 'Luoghi' },
    { word: 'GIARDINO', categoria: 'Luoghi' },
    { word: 'PARCHEGGIO', categoria: 'Luoghi' },
    { word: 'CARCERE', categoria: 'Luoghi' },
    { word: 'RISTORANTE', categoria: 'Luoghi' },
    { word: 'BANCA', categoria: 'Luoghi' },

    // ── Mestieri ─────────────────────────────────────────────────────────
    { word: 'ASTRONAUTA', categoria: 'Mestieri' },
    { word: 'DENTISTA', categoria: 'Mestieri' },
    { word: 'MAESTRA', categoria: 'Mestieri' },
    { word: 'POETA', categoria: 'Mestieri' },
    { word: 'PITTORE', categoria: 'Mestieri' },
    { word: 'SCULTORE', categoria: 'Mestieri' },
    { word: 'MURATORE', categoria: 'Mestieri' },
    { word: 'IDRAULICO', categoria: 'Mestieri' },
    { word: 'ELETTRICISTA', categoria: 'Mestieri' },
    { word: 'CUOCO', categoria: 'Mestieri' },
    { word: 'PASTICCIERE', categoria: 'Mestieri' },
    { word: 'FORNAIO', categoria: 'Mestieri' },
    { word: 'IMPIEGATO', categoria: 'Mestieri' },
    { word: 'DIRETTORE', categoria: 'Mestieri' },
    { word: 'GIORNALISTA', categoria: 'Mestieri' },
    { word: 'SCRITTORE', categoria: 'Mestieri' },
    { word: 'MUSICISTA', categoria: 'Mestieri' },
    { word: 'CANTANTE', categoria: 'Mestieri' },
    { word: 'BALLERINA', categoria: 'Mestieri' },
    { word: 'ATTORE', categoria: 'Mestieri' },
    { word: 'MAGO', categoria: 'Mestieri' },
    { word: 'VETERINARIO', categoria: 'Mestieri' },
    { word: 'ARCHITETTO', categoria: 'Mestieri' },
    { word: 'INGEGNERE', categoria: 'Mestieri' },
    { word: 'AVVOCATO', categoria: 'Mestieri' },
    { word: 'GIUDICE', categoria: 'Mestieri' },
    { word: 'POLIZIOTTO', categoria: 'Mestieri' },
    { word: 'VIGILE', categoria: 'Mestieri' },
    { word: 'MECCANICO', categoria: 'Mestieri' },
    { word: 'FALEGNAME', categoria: 'Mestieri' },
    { word: 'SARTORE', categoria: 'Mestieri' },
    { word: 'CALZOLAIO', categoria: 'Mestieri' },

    // ── Musica ───────────────────────────────────────────────────────────
    { word: 'CHITARRA', categoria: 'Musica' },
    { word: 'PIANOFORTE', categoria: 'Musica' },
    { word: 'VIOLINO', categoria: 'Musica' },
    { word: 'VIOLONCELLO', categoria: 'Musica' },
    { word: 'FLAUTO', categoria: 'Musica' },
    { word: 'TROMBA', categoria: 'Musica' },
    { word: 'SASSOFONO', categoria: 'Musica' },
    { word: 'BATTERIA', categoria: 'Musica' },
    { word: 'CAMPANELLA', categoria: 'Musica' },
    { word: 'OPERA', categoria: 'Musica' },
    { word: 'SINFONIA', categoria: 'Musica' },
    { word: 'SPARTITO', categoria: 'Musica' },
    { word: 'NOTE', categoria: 'Musica' },
    { word: 'ACCORDO', categoria: 'Musica' },
    { word: 'MELODIA', categoria: 'Musica' },
    { word: 'RITMO', categoria: 'Musica' },
    { word: 'CONCERTO', categoria: 'Musica' },
    { word: 'RADIO', categoria: 'Musica' },
    { word: 'CANTANTE', categoria: 'Musica' },

    // ── Sport ────────────────────────────────────────────────────────────
    { word: 'BICICLETTA', categoria: 'Sport' },
    { word: 'CAMPIONE', categoria: 'Sport' },
    { word: 'CALCIO', categoria: 'Sport' },
    { word: 'PALLONE', categoria: 'Sport' },
    { word: 'PORTIERE', categoria: 'Sport' },
    { word: 'ALLENATORE', categoria: 'Sport' },
    { word: 'MARATONA', categoria: 'Sport' },
    { word: 'ATLETICA', categoria: 'Sport' },
    { word: 'NUOTO', categoria: 'Sport' },
    { word: 'PISCINA', categoria: 'Sport' },
    { word: 'SCI', categoria: 'Sport' },
    { word: 'SNOWBOARD', categoria: 'Sport' },
    { word: 'TENNIS', categoria: 'Sport' },
    { word: 'RACCHETTA', categoria: 'Sport' },
    { word: 'PALLACANESTRO', categoria: 'Sport' },
    { word: 'PALLANUOTO', categoria: 'Sport' },
    { word: 'CICLISMO', categoria: 'Sport' },
    { word: 'SCACCHI', categoria: 'Sport' },
    { word: 'PUGILATO', categoria: 'Sport' },
    { word: 'GINNASTICA', categoria: 'Sport' },
    { word: 'VOLLEY', categoria: 'Sport' },
    { word: 'RUGBY', categoria: 'Sport' },
    { word: 'AEROBICA', categoria: 'Sport' },
    { word: 'PATTINAGGIO', categoria: 'Sport' },

    // ── Auto ─────────────────────────────────────────────────────────────
    { word: 'FERRARI', categoria: 'Auto' },
    { word: 'LAMBORGHINI', categoria: 'Auto' },
    { word: 'MASERATI', categoria: 'Auto' },
    { word: 'VOLANTE', categoria: 'Auto' },
    { word: 'MOTORE', categoria: 'Auto' },
    { word: 'FRENO', categoria: 'Auto' },
    { word: 'CAMBIO', categoria: 'Auto' },
    { word: 'FANALE', categoria: 'Auto' },
    { word: 'PARAFANGHI', categoria: 'Auto' },
    { word: 'GARAGE', categoria: 'Auto' },
    { word: 'RUOTE', categoria: 'Auto' },
    { word: 'PATENTE', categoria: 'Auto' },
    { word: 'SEMAFORO', categoria: 'Auto' },
    { word: 'AUTOSTRADA', categoria: 'Auto' },

    // ── Mezzi ────────────────────────────────────────────────────────────
    { word: 'TRENO', categoria: 'Mezzi' },
    { word: 'BARCA', categoria: 'Mezzi' },
    { word: 'AEREO', categoria: 'Mezzi' },
    { word: 'AUTOBUS', categoria: 'Mezzi' },
    { word: 'METROPOLITANA', categoria: 'Mezzi' },
    { word: 'TRAM', categoria: 'Mezzi' },
    { word: 'NAVE', categoria: 'Mezzi' },
    { word: 'SOMMERGIBILE', categoria: 'Mezzi' },
    { word: 'ELICOTTERO', categoria: 'Mezzi' },
    { word: 'MONOPATTINO', categoria: 'Mezzi' },
    { word: 'TAXI', categoria: 'Mezzi' },
    { word: 'CAMION', categoria: 'Mezzi' },
    { word: 'FURGONE', categoria: 'Mezzi' },

    // ── Mitologia ────────────────────────────────────────────────────────
    { word: 'DRAGO', categoria: 'Mitologia' },
    { word: 'MUMMIA', categoria: 'Mitologia' },
    { word: 'FENICE', categoria: 'Mitologia' },
    { word: 'UNICORNO', categoria: 'Mitologia' },
    { word: 'PEGASO', categoria: 'Mitologia' },
    { word: 'CENTAURO', categoria: 'Mitologia' },
    { word: 'MINOTAURO', categoria: 'Mitologia' },
    { word: 'SIRENA', categoria: 'Mitologia' },
    { word: 'MEDUSA', categoria: 'Mitologia' },
    { word: 'ZEUS', categoria: 'Mitologia' },
    { word: 'ATENA', categoria: 'Mitologia' },
    { word: 'ERCOLE', categoria: 'Mitologia' },
    { word: 'ABISSO', categoria: 'Mitologia' },
    { word: 'OLIMPO', categoria: 'Mitologia' },

    // ── Altro ────────────────────────────────────────────────────────────
    { word: 'FANTASMA', categoria: 'Altro' },
    { word: 'ZOMBIE', categoria: 'Altro' },
    { word: 'BEFANA', categoria: 'Altro' },
    { word: 'STREGA', categoria: 'Altro' },
    { word: 'FATA', categoria: 'Altro' },
    { word: 'MISTERIO', categoria: 'Altro' },
    { word: 'SEGRETO', categoria: 'Altro' },
    { word: 'AVVENTURA', categoria: 'Altro' },
    { word: 'VIAGGIO', categoria: 'Altro' },
    { word: 'VACANZA', categoria: 'Altro' },
    { word: 'FESTA', categoria: 'Altro' },
    { word: 'COMPLEANNO', categoria: 'Altro' },
    { word: 'MATRIMONIO', categoria: 'Altro' },
    { word: 'REGGALO', categoria: 'Altro' },
    { word: 'SORPRESA', categoria: 'Altro' },
    { word: 'FORZA', categoria: 'Altro' },
    { word: 'CORAGGIO', categoria: 'Altro' },
    { word: 'AMICIZIA', categoria: 'Altro' },
    { word: 'PERICOLO', categoria: 'Altro' },
    { word: 'GIOIA', categoria: 'Altro' },
    { word: 'TRISTEZZA', categoria: 'Altro' },
    { word: 'PAURA', categoria: 'Altro' },
    { word: 'RABBIA', categoria: 'Altro' },
    { word: 'PAZIENTE', categoria: 'Altro' },
    { word: 'RICCHEZZA', categoria: 'Altro' },
    { word: 'GENEROSITA', categoria: 'Altro' },

    // ── Personaggi ───────────────────────────────────────────────────────
    { word: 'PINOCCHIO', categoria: 'Personaggi' },
    { word: 'CENERENTOLA', categoria: 'Personaggi' },
    { word: 'BIANCANEVE', categoria: 'Personaggi' },
    { word: 'MARIO', categoria: 'Personaggi' },
    { word: 'LUIGI', categoria: 'Personaggi' },
    { word: 'SHREK', categoria: 'Personaggi' },
    { word: 'BATMAN', categoria: 'Personaggi' },
    { word: 'HULK', categoria: 'Personaggi' },
    { word: 'THOR', categoria: 'Personaggi' },
    { word: 'WONDERWOMAN', categoria: 'Personaggi' },
    { word: 'SUPERMAN', categoria: 'Personaggi' },
    { word: 'SPIDERMAN', categoria: 'Personaggi' },
    { word: 'IRONMAN', categoria: 'Personaggi' },
    { word: 'PIPPO', categoria: 'Personaggi' },
    { word: 'PLUTO', categoria: 'Personaggi' },
    { word: 'TOPOLINO', categoria: 'Personaggi' },
    { word: 'PAPERINO', categoria: 'Personaggi' },
    { word: 'ZORRO', categoria: 'Personaggi' },
    { word: 'TARZAN', categoria: 'Personaggi' },
    { word: 'ROBINHOOD', categoria: 'Personaggi' },
    { word: 'GULLIVER', categoria: 'Personaggi' },
    { word: 'POCAHONTAS', categoria: 'Personaggi' },
    { word: 'ALADINO', categoria: 'Personaggi' },
    { word: 'SINDBAD', categoria: 'Personaggi' },

    // ── Personaggi (aggiunte) ────────────────────────────────────────────
    { word: 'ELSA', categoria: 'Personaggi' },
    { word: 'ANNA', categoria: 'Personaggi' },
    { word: 'OLAF', categoria: 'Personaggi' },
    { word: 'GRU', categoria: 'Personaggi' },
    { word: 'MINIONS', categoria: 'Personaggi' },
    { word: 'GOOFY', categoria: 'Personaggi' },
    { word: 'MINNIE', categoria: 'Personaggi' },
    { word: 'DAISY', categoria: 'Personaggi' },
    { word: 'DONALD', categoria: 'Personaggi' },
    { word: 'GASTON', categoria: 'Personaggi' },
    { word: 'BELLE', categoria: 'Personaggi' },
    { word: 'AURORA', categoria: 'Personaggi' },
    { word: 'ARIEL', categoria: 'Personaggi' },
    { word: 'MULAN', categoria: 'Personaggi' },
    { word: 'RAPUNZEL', categoria: 'Personaggi' },
    { word: 'TIANA', categoria: 'Personaggi' },
    { word: 'MERIDA', categoria: 'Personaggi' },
    { word: 'MOANA', categoria: 'Personaggi' },
    { word: 'FROZEN', categoria: 'Personaggi' },

    // ── Animali (aggiunte) ───────────────────────────────────────────────
    { word: 'IGUANA', categoria: 'Animali' },
    { word: 'LONTRA', categoria: 'Animali' },
    { word: 'FURETTO', categoria: 'Animali' },
    { word: 'COYOTE', categoria: 'Animali' },
    { word: 'SCIACALLO', categoria: 'Animali' },
    { word: 'LEMURE', categoria: 'Animali' },
    { word: 'TAPIRO', categoria: 'Animali' },
    { word: 'BABBUINO', categoria: 'Animali' },
    { word: 'GHEPARDO', categoria: 'Animali' },
    { word: 'VIPERA', categoria: 'Animali' },
    { word: 'BOA', categoria: 'Animali' },
    { word: 'MAMBA', categoria: 'Animali' },
    { word: 'TARANTOLA', categoria: 'Animali' },
    { word: 'LUMACA', categoria: 'Animali' },
    { word: 'CHIOCCIOLA', categoria: 'Animali' },
    { word: 'VERME', categoria: 'Animali' },
    { word: 'LOMBRICO', categoria: 'Animali' },
    { word: 'GIAGUARO', categoria: 'Animali' },
    { word: 'PANTERA', categoria: 'Animali' },
    { word: 'LINCE', categoria: 'Animali' },
    { word: 'LEOPARDO', categoria: 'Animali' },
    { word: 'PUMA', categoria: 'Animali' },
    { word: 'CINGHIALE', categoria: 'Animali' },
    { word: 'CERVO', categoria: 'Animali' },
    { word: 'CAPRIOLO', categoria: 'Animali' },
    { word: 'DAINO', categoria: 'Animali' },
    { word: 'MARMOTTA', categoria: 'Animali' },
    { word: 'PORCOSPINO', categoria: 'Animali' },
    { word: 'TASSO', categoria: 'Animali' },
    { word: 'DONNOLA', categoria: 'Animali' },
    { word: 'ORNITORINCO', categoria: 'Animali' },
    { word: 'ECHIDNA', categoria: 'Animali' },
    { word: 'CAVALLUCCIO', categoria: 'Animali' },
    { word: 'MANTARAY', categoria: 'Animali' },
    { word: 'BARRACUDA', categoria: 'Animali' },
    { word: 'MERLUZZO', categoria: 'Animali' },
    { word: 'SARDINA', categoria: 'Animali' },
    { word: 'ACCIUGHE', categoria: 'Animali' },
    { word: 'ARAGOSTA', categoria: 'Animali' },
    { word: 'GAMBERO', categoria: 'Animali' },
    { word: 'CALAMARO', categoria: 'Animali' },
    { word: 'SEPPIA', categoria: 'Animali' },
    { word: 'CORALLO', categoria: 'Animali' },
    { word: 'STELLAMARINA', categoria: 'Animali' },
    { word: 'ASTICE', categoria: 'Animali' },
    { word: 'ORATA', categoria: 'Animali' },
    { word: 'SPIGOLA', categoria: 'Animali' },
    { word: 'TONNO', categoria: 'Animali' },
    { word: 'SGOMBRO', categoria: 'Animali' },
    { word: 'ANGUILLA', categoria: 'Animali' },
    { word: 'TRIGLIA', categoria: 'Animali' },
    { word: 'SALMONE', categoria: 'Animali' },
    { word: 'ROMBO', categoria: 'Animali' },
    { word: 'GRANCHIO', categoria: 'Animali' },

    // ── Cibo (aggiunte) ──────────────────────────────────────────────────
    { word: 'ARANCINO', categoria: 'Cibo' },
    { word: 'SFOGLIATELLA', categoria: 'Cibo' },
    { word: 'PIADINA', categoria: 'Cibo' },
    { word: 'TIGELLA', categoria: 'Cibo' },
    { word: 'FARINATA', categoria: 'Cibo' },
    { word: 'PIZZETTA', categoria: 'Cibo' },
    { word: 'CALZONE', categoria: 'Cibo' },
    { word: 'SCHIACCIATA', categoria: 'Cibo' },
    { word: 'BRUSCHETTA', categoria: 'Cibo' },
    { word: 'CARPACCIO', categoria: 'Cibo' },
    { word: 'TARTARE', categoria: 'Cibo' },
    { word: 'SASHIMI', categoria: 'Cibo' },
    { word: 'SUSHI', categoria: 'Cibo' },
    { word: 'RAMEN', categoria: 'Cibo' },
    { word: 'DIMSUM', categoria: 'Cibo' },
    { word: 'GUACAMOLE', categoria: 'Cibo' },
    { word: 'TACOS', categoria: 'Cibo' },
    { word: 'BURRITO', categoria: 'Cibo' },
    { word: 'NACHOS', categoria: 'Cibo' },
    { word: 'KEBAB', categoria: 'Cibo' },
    { word: 'FALAFEL', categoria: 'Cibo' },
    { word: 'HUMMUS', categoria: 'Cibo' },
    { word: 'TZATZIKI', categoria: 'Cibo' },
    { word: 'PAELLA', categoria: 'Cibo' },
    { word: 'TAPAS', categoria: 'Cibo' },
    { word: 'BAGUETTE', categoria: 'Cibo' },
    { word: 'CROSTATA', categoria: 'Cibo' },
    { word: 'SORBETTO', categoria: 'Cibo' },
    { word: 'GRANITA', categoria: 'Cibo' },
    { word: 'ZABAIONE', categoria: 'Cibo' },
    { word: 'PANDORO', categoria: 'Cibo' },
    { word: 'TORRONE', categoria: 'Cibo' },
    { word: 'MARZAPANE', categoria: 'Cibo' },
    { word: 'AMARETTO', categoria: 'Cibo' },
    { word: 'LIQUIRIZIA', categoria: 'Cibo' },
    { word: 'CARAMELLO', categoria: 'Cibo' },
    { word: 'POPCORN', categoria: 'Cibo' },
    { word: 'MORTADELLA', categoria: 'Cibo' },
    { word: 'BURRATA', categoria: 'Cibo' },
    { word: 'TALEGGIO', categoria: 'Cibo' },
    { word: 'GORGONZOLA', categoria: 'Cibo' },
    { word: 'PECORINO', categoria: 'Cibo' },
    { word: 'GRANA', categoria: 'Cibo' },
    { word: 'RICOTTA', categoria: 'Cibo' },
    { word: 'WAFER', categoria: 'Cibo' },

    // ── Tecnologia (aggiunte) ────────────────────────────────────────────
    { word: 'SATELLITE', categoria: 'Tecnologia' },
    { word: 'MODEM', categoria: 'Tecnologia' },
    { word: 'ROUTER', categoria: 'Tecnologia' },
    { word: 'FIREWALL', categoria: 'Tecnologia' },
    { word: 'PASSWORD', categoria: 'Tecnologia' },
    { word: 'USERNAME', categoria: 'Tecnologia' },
    { word: 'SCREENSHOT', categoria: 'Tecnologia' },
    { word: 'DOWNLOAD', categoria: 'Tecnologia' },
    { word: 'UPLOAD', categoria: 'Tecnologia' },
    { word: 'STREAMING', categoria: 'Tecnologia' },
    { word: 'BLUETOOTH', categoria: 'Tecnologia' },
    { word: 'WIRELESS', categoria: 'Tecnologia' },
    { word: 'CHIP', categoria: 'Tecnologia' },
    { word: 'SCHEDAMADRE', categoria: 'Tecnologia' },
    { word: 'ALTAVOCE', categoria: 'Tecnologia' },
    { word: 'MICROFONO', categoria: 'Tecnologia' },
    { word: 'WEBCAM', categoria: 'Tecnologia' },
    { word: 'MONITOR', categoria: 'Tecnologia' },
    { word: 'JOYSTICK', categoria: 'Tecnologia' },
    { word: 'LAPTOP', categoria: 'Tecnologia' },
    { word: 'SMARTHOME', categoria: 'Tecnologia' },
    { word: 'CHATBOT', categoria: 'Tecnologia' },
    { word: 'BOT', categoria: 'Tecnologia' },
    { word: 'GPS', categoria: 'Tecnologia' },
    { word: 'LED', categoria: 'Tecnologia' },
    { word: 'KEYBOARD', categoria: 'Tecnologia' },
    { word: 'SENSORE', categoria: 'Tecnologia' },

    // ── Natura (aggiunte) ────────────────────────────────────────────────
    { word: 'MONTAGNA', categoria: 'Natura' },
    { word: 'ROCCIA', categoria: 'Natura' },
    { word: 'GROTTA', categoria: 'Natura' },
    { word: 'CANYON', categoria: 'Natura' },
    { word: 'DESERTO', categoria: 'Natura' },
    { word: 'DUNA', categoria: 'Natura' },
    { word: 'PALUDE', categoria: 'Natura' },
    { word: 'LAGUNA', categoria: 'Natura' },
    { word: 'CORRENTE', categoria: 'Natura' },
    { word: 'GEISER', categoria: 'Natura' },
    { word: 'VULCANO', categoria: 'Natura' },
    { word: 'CRATERE', categoria: 'Natura' },
    { word: 'METEORITE', categoria: 'Natura' },
    { word: 'FUNGO', categoria: 'Natura' },
    { word: 'MUSCHIO', categoria: 'Natura' },
    { word: 'CACTUS', categoria: 'Natura' },
    { word: 'BAMBU', categoria: 'Natura' },
    { word: 'EUCALIPTO', categoria: 'Natura' },
    { word: 'BAOBAB', categoria: 'Natura' },
    { word: 'MANGROVIA', categoria: 'Natura' },
    { word: 'SCOGLIO', categoria: 'Natura' },
    { word: 'FARAGLIONI', categoria: 'Natura' },
    { word: 'SPIAGGIA', categoria: 'Natura' },
    { word: 'PRATIERA', categoria: 'Natura' },
    { word: 'SAVANA', categoria: 'Natura' },
    { word: 'TUNDRA', categoria: 'Natura' },

    // ── Spazio (aggiunte) ────────────────────────────────────────────────
    { word: 'ESOPIANETA', categoria: 'Spazio' },
    { word: 'PULSAR', categoria: 'Spazio' },
    { word: 'QUASAR', categoria: 'Spazio' },
    { word: 'BUCONERO', categoria: 'Spazio' },
    { word: 'ANTIMATERIA', categoria: 'Spazio' },
    { word: 'MATERIA', categoria: 'Spazio' },
    { word: 'BIGBANG', categoria: 'Spazio' },
    { word: 'COSMONAUTA', categoria: 'Spazio' },
    { word: 'ORION', categoria: 'Spazio' },
    { word: 'ANDROMEDA', categoria: 'Spazio' },
    { word: 'VIALATTEA', categoria: 'Spazio' },
    { word: 'APOLLO', categoria: 'Spazio' },

    // ── Sport (aggiunte) ─────────────────────────────────────────────────
    { word: 'FUTSAL', categoria: 'Sport' },
    { word: 'BASKET', categoria: 'Sport' },
    { word: 'TRIATHLON', categoria: 'Sport' },
    { word: 'DECATHLON', categoria: 'Sport' },
    { word: 'TUFFI', categoria: 'Sport' },
    { word: 'CANOTTAGGIO', categoria: 'Sport' },
    { word: 'VELA', categoria: 'Sport' },
    { word: 'SURF', categoria: 'Sport' },
    { word: 'KITESURF', categoria: 'Sport' },
    { word: 'WINDSURF', categoria: 'Sport' },
    { word: 'ARRAMPICATA', categoria: 'Sport' },
    { word: 'PARKOUR', categoria: 'Sport' },
    { word: 'SKATEBOARD', categoria: 'Sport' },
    { word: 'MOTOCROSS', categoria: 'Sport' },
    { word: 'FORMULAUNO', categoria: 'Sport' },
    { word: 'KART', categoria: 'Sport' },
    { word: 'BOWLING', categoria: 'Sport' },
    { word: 'BOCCIA', categoria: 'Sport' },
    { word: 'BILIARDO', categoria: 'Sport' },
    { word: 'DARTS', categoria: 'Sport' },
    { word: 'MINIGOLF', categoria: 'Sport' },
    { word: 'PADEL', categoria: 'Sport' },
    { word: 'TENNISTAVOLO', categoria: 'Sport' },
    { word: 'HOCKEY', categoria: 'Sport' },
    { word: 'SQUASH', categoria: 'Sport' },
    { word: 'CRICKET', categoria: 'Sport' },
    { word: 'BASEBALL', categoria: 'Sport' },
    { word: 'FOOTBALL', categoria: 'Sport' },

    // ── Musica (aggiunte) ────────────────────────────────────────────────
    { word: 'RAP', categoria: 'Musica' },
    { word: 'TRAP', categoria: 'Musica' },
    { word: 'HIPHOP', categoria: 'Musica' },
    { word: 'ROCK', categoria: 'Musica' },
    { word: 'METAL', categoria: 'Musica' },
    { word: 'PUNK', categoria: 'Musica' },
    { word: 'JAZZ', categoria: 'Musica' },
    { word: 'BLUES', categoria: 'Musica' },
    { word: 'REGGAE', categoria: 'Musica' },
    { word: 'SKA', categoria: 'Musica' },
    { word: 'DISCO', categoria: 'Musica' },
    { word: 'HOUSE', categoria: 'Musica' },
    { word: 'TECHNO', categoria: 'Musica' },
    { word: 'EDM', categoria: 'Musica' },
    { word: 'CLASSICA', categoria: 'Musica' },
    { word: 'ORCHESTRA', categoria: 'Musica' },
    { word: 'MAESTRO', categoria: 'Musica' },
    { word: 'BATTERISTA', categoria: 'Musica' },
    { word: 'CHITARRISTA', categoria: 'Musica' },
    { word: 'PIANISTA', categoria: 'Musica' },
    { word: 'VINILE', categoria: 'Musica' },
    { word: 'FESTIVAL', categoria: 'Musica' },
    { word: 'AUTOTUNE', categoria: 'Musica' },
    { word: 'BEAT', categoria: 'Musica' },
    { word: 'PLAYLIST', categoria: 'Musica' },
    { word: 'SPOTIFY', categoria: 'Musica' },
    { word: 'YOUTUBE', categoria: 'Musica' },
    { word: 'ARMONIA', categoria: 'Musica' },
    { word: 'KARAOKE', categoria: 'Musica' },
    { word: 'DUETTO', categoria: 'Musica' },
    { word: 'ASSOLO', categoria: 'Musica' },

    // ── Mestieri (aggiunte) ──────────────────────────────────────────────
    { word: 'PILOTA', categoria: 'Mestieri' },
    { word: 'CAPITANO', categoria: 'Mestieri' },
    { word: 'TIMONIERE', categoria: 'Mestieri' },
    { word: 'STEWARD', categoria: 'Mestieri' },
    { word: 'FOTOGRAFO', categoria: 'Mestieri' },
    { word: 'REGISTA', categoria: 'Mestieri' },
    { word: 'TECNICO', categoria: 'Mestieri' },
    { word: 'PROGRAMMATORE', categoria: 'Mestieri' },
    { word: 'ANALISTA', categoria: 'Mestieri' },
    { word: 'STATISTICO', categoria: 'Mestieri' },
    { word: 'CONTABILE', categoria: 'Mestieri' },
    { word: 'RAGIONIERE', categoria: 'Mestieri' },
    { word: 'GEOMETRA', categoria: 'Mestieri' },
    { word: 'NOTAIO', categoria: 'Mestieri' },
    { word: 'AGENTE', categoria: 'Mestieri' },
    { word: 'GIARDINIERE', categoria: 'Mestieri' },
    { word: 'PESCATORE', categoria: 'Mestieri' },
    { word: 'AGRICOLTORE', categoria: 'Mestieri' },
    { word: 'PASTORE', categoria: 'Mestieri' },
    { word: 'MINATORE', categoria: 'Mestieri' },
    { word: 'PARACADUTISTA', categoria: 'Mestieri' },
    { word: 'SOCCORRITORE', categoria: 'Mestieri' },
    { word: 'POMPIERE', categoria: 'Mestieri' },
    { word: 'CARABINIERE', categoria: 'Mestieri' },
    { word: 'MILITARE', categoria: 'Mestieri' },
    { word: 'GENERALE', categoria: 'Mestieri' },
    { word: 'BARISTA', categoria: 'Mestieri' },
    { word: 'PIZZAIOLO', categoria: 'Mestieri' },
    { word: 'CASSIERE', categoria: 'Mestieri' },

    // ── Luoghi (aggiunte) ────────────────────────────────────────────────
    { word: 'PALAZZO', categoria: 'Luoghi' },
    { word: 'GRATTACIELO', categoria: 'Luoghi' },
    { word: 'VILLA', categoria: 'Luoghi' },
    { word: 'MANSIONE', categoria: 'Luoghi' },
    { word: 'FORTEZZA', categoria: 'Luoghi' },
    { word: 'FONTANA', categoria: 'Luoghi' },
    { word: 'PIAZZA', categoria: 'Luoghi' },
    { word: 'VIALE', categoria: 'Luoghi' },
    { word: 'VICOLO', categoria: 'Luoghi' },
    { word: 'BOTTEGA', categoria: 'Luoghi' },
    { word: 'NEGOZIO', categoria: 'Luoghi' },
    { word: 'PESCHERIA', categoria: 'Luoghi' },
    { word: 'MACCELLERIA', categoria: 'Luoghi' },
    { word: 'PANETTERIA', categoria: 'Luoghi' },
    { word: 'PASTICCERIA', categoria: 'Luoghi' },
    { word: 'GELATERIA', categoria: 'Luoghi' },
    { word: 'TAVERNA', categoria: 'Luoghi' },
    { word: 'OSTERIA', categoria: 'Luoghi' },
    { word: 'TRATTORIA', categoria: 'Luoghi' },
    { word: 'PALESTRA', categoria: 'Luoghi' },
    { word: 'AEROPORTO', categoria: 'Luoghi' },
    { word: 'STAZIONE', categoria: 'Luoghi' },
    { word: 'GALLERIA', categoria: 'Luoghi' },
    { word: 'PARCO', categoria: 'Luoghi' },
    { word: 'ORTO', categoria: 'Luoghi' },
    { word: 'CIMITERO', categoria: 'Luoghi' },
    { word: 'LUNAPARK', categoria: 'Luoghi' },
    { word: 'CIRCO', categoria: 'Luoghi' },
    { word: 'ZOO', categoria: 'Luoghi' },
    { word: 'SAFARI', categoria: 'Luoghi' },
    { word: 'AQUARIUM', categoria: 'Luoghi' },
    { word: 'FIERA', categoria: 'Luoghi' },
    { word: 'SAGRA', categoria: 'Luoghi' },
    { word: 'BASILICA', categoria: 'Luoghi' },
    { word: 'DUOMO', categoria: 'Luoghi' },
    { word: 'MOSCHEA', categoria: 'Luoghi' },

    // ── Mezzi (aggiunte) ─────────────────────────────────────────────────
    { word: 'CICLOMOTORE', categoria: 'Mezzi' },
    { word: 'SCOOTER', categoria: 'Mezzi' },
    { word: 'SEGWAY', categoria: 'Mezzi' },
    { word: 'FURGONETTO', categoria: 'Mezzi' },
    { word: 'AUTO', categoria: 'Mezzi' },
    { word: 'MACCHINA', categoria: 'Mezzi' },
    { word: 'LIMOUSINE', categoria: 'Mezzi' },
    { word: 'MINIVAN', categoria: 'Mezzi' },
    { word: 'TIR', categoria: 'Mezzi' },
    { word: 'RIMORCHIO', categoria: 'Mezzi' },
    { word: 'CROCIERA', categoria: 'Mezzi' },
    { word: 'ZATTERA', categoria: 'Mezzi' },
    { word: 'KAYAK', categoria: 'Mezzi' },
    { word: 'CANOA', categoria: 'Mezzi' },
    { word: 'GONDOLA', categoria: 'Mezzi' },
    { word: 'MOTOSCAFO', categoria: 'Mezzi' },
    { word: 'IDROVOLANTE', categoria: 'Mezzi' },
    { word: 'JET', categoria: 'Mezzi' },
    { word: 'MOTORINO', categoria: 'Mezzi' },

    // ── Mitologia (aggiunte) ─────────────────────────────────────────────
    { word: 'TITANO', categoria: 'Mitologia' },
    { word: 'GIANTE', categoria: 'Mitologia' },
    { word: 'NINFA', categoria: 'Mitologia' },
    { word: 'TRITONE', categoria: 'Mitologia' },
    { word: 'CICLOPE', categoria: 'Mitologia' },
    { word: 'IDRA', categoria: 'Mitologia' },
    { word: 'CHIMERA', categoria: 'Mitologia' },
    { word: 'GORGONE', categoria: 'Mitologia' },
    { word: 'ARPIA', categoria: 'Mitologia' },
    { word: 'VALCHIRIA', categoria: 'Mitologia' },
    { word: 'ODINO', categoria: 'Mitologia' },
    { word: 'THOR', categoria: 'Mitologia' },
    { word: 'LOKI', categoria: 'Mitologia' },
    { word: 'POSEIDONE', categoria: 'Mitologia' },
    { word: 'ADE', categoria: 'Mitologia' },
    { word: 'CRONO', categoria: 'Mitologia' },
    { word: 'ARTEMIDE', categoria: 'Mitologia' },
    { word: 'APOLLO', categoria: 'Mitologia' },

    // ── Altro (aggiunte) ─────────────────────────────────────────────────
    { word: 'FORTUNA', categoria: 'Altro' },
    { word: 'SFORTUNA', categoria: 'Altro' },
    { word: 'COINCIDENZA', categoria: 'Altro' },
    { word: 'DESTINO', categoria: 'Altro' },
    { word: 'SOGNO', categoria: 'Altro' },
    { word: 'INCUBO', categoria: 'Altro' },
    { word: 'RICORDO', categoria: 'Altro' },
    { word: 'RIMORSO', categoria: 'Altro' },
    { word: 'NOSTALGIA', categoria: 'Altro' },
    { word: 'EMOZIONE', categoria: 'Altro' },
    { word: 'SENTIMENTO', categoria: 'Altro' },
    { word: 'PASSIONE', categoria: 'Altro' },
    { word: 'ALLEGRIA', categoria: 'Altro' },
    { word: 'NOIA', categoria: 'Altro' },
    { word: 'DIVERTIMENTO', categoria: 'Altro' },
    { word: 'SCHERZO', categoria: 'Altro' },
    { word: 'RIDERE', categoria: 'Altro' },
    { word: 'SORRISO', categoria: 'Altro' },
    { word: 'ABBRACCIO', categoria: 'Altro' },
    { word: 'BACIO', categoria: 'Altro' },
    { word: 'CAPRICCIO', categoria: 'Altro' },
    { word: 'FISSAZIONE', categoria: 'Altro' },
    { word: 'OSSESSIONE', categoria: 'Altro' },
    { word: 'PARANOIA', categoria: 'Altro' },
    { word: 'ANSIA', categoria: 'Altro' },
    { word: 'STRESS', categoria: 'Altro' },

    // ── Videogiochi (nuova) ──────────────────────────────────────────────
    { word: 'MINECRAFT', categoria: 'Videogiochi' },
    { word: 'FORTNITE', categoria: 'Videogiochi' },
    { word: 'POKEMON', categoria: 'Videogiochi' },
    { word: 'ROBLOX', categoria: 'Videogiochi' },
    { word: 'TETRIS', categoria: 'Videogiochi' },
    { word: 'PACMAN', categoria: 'Videogiochi' },
    { word: 'SONIC', categoria: 'Videogiochi' },
    { word: 'ZELDA', categoria: 'Videogiochi' },
    { word: 'DOOM', categoria: 'Videogiochi' },
    { word: 'CRASH', categoria: 'Videogiochi' },
    { word: 'RAYMAN', categoria: 'Videogiochi' },
    { word: 'METROID', categoria: 'Videogiochi' },
    { word: 'KIRBY', categoria: 'Videogiochi' },
    { word: 'MEGAMAN', categoria: 'Videogiochi' },
    { word: 'AMONGUS', categoria: 'Videogiochi' },
    { word: 'FALLGUYS', categoria: 'Videogiochi' },
    { word: 'SUBWAY', categoria: 'Videogiochi' },
    { word: 'SNAKE', categoria: 'Videogiochi' },
    { word: 'ANGRIBIRDS', categoria: 'Videogiochi' },
    { word: 'CANDYCRUSH', categoria: 'Videogiochi' },
    { word: 'SPLATOON', categoria: 'Videogiochi' },
    { word: 'BRAWLSTARS', categoria: 'Videogiochi' },
    { word: 'CLASHROYALE', categoria: 'Videogiochi' },
    { word: 'SUPERMARIO', categoria: 'Videogiochi' },
    { word: 'PONG', categoria: 'Videogiochi' },

    // ── Social (nuova) ───────────────────────────────────────────────────
    { word: 'TIKTOK', categoria: 'Social' },
    { word: 'SELFIE', categoria: 'Social' },
    { word: 'MEME', categoria: 'Social' },
    { word: 'VIRALE', categoria: 'Social' },
    { word: 'TRENDING', categoria: 'Social' },
    { word: 'HASHTAG', categoria: 'Social' },
    { word: 'FILTRO', categoria: 'Social' },
    { word: 'FOLLOWERS', categoria: 'Social' },
    { word: 'STREAMER', categoria: 'Social' },
    { word: 'TUTORIAL', categoria: 'Social' },
    { word: 'TREND', categoria: 'Social' },
    { word: 'DIRECT', categoria: 'Social' },
    { word: 'LIVE', categoria: 'Social' },
    { word: 'POST', categoria: 'Social' },
    { word: 'LIKE', categoria: 'Social' },
    { word: 'SHARE', categoria: 'Social' },
    { word: 'COMMENTO', categoria: 'Social' },
    { word: 'INFLUENCER', categoria: 'Social' },
    { word: 'CREATOR', categoria: 'Social' },
    { word: 'NOTIFICA', categoria: 'Social' },
    { word: 'STATUS', categoria: 'Social' },
    { word: 'STORIA', categoria: 'Social' },
    { word: 'EMOJI', categoria: 'Social' },
    { word: 'STICKER', categoria: 'Social' },
    { word: 'GIF', categoria: 'Social' },
    { word: 'DUET', categoria: 'Social' },
    { word: 'SCROLLARE', categoria: 'Social' },

    // ── Scuola (nuova) ───────────────────────────────────────────────────
    { word: 'COMPITI', categoria: 'Scuola' },
    { word: 'VERIFICA', categoria: 'Scuola' },
    { word: 'ZAINO', categoria: 'Scuola' },
    { word: 'DIARIO', categoria: 'Scuola' },
    { word: 'PENNA', categoria: 'Scuola' },
    { word: 'MATITA', categoria: 'Scuola' },
    { word: 'GOMMA', categoria: 'Scuola' },
    { word: 'RIGHELLO', categoria: 'Scuola' },
    { word: 'COMPAGNO', categoria: 'Scuola' },
    { word: 'PROFESSORE', categoria: 'Scuola' },
    { word: 'LAVAGNA', categoria: 'Scuola' },
    { word: 'CATTEDRA', categoria: 'Scuola' },
    { word: 'BANCO', categoria: 'Scuola' },
    { word: 'LIBRO', categoria: 'Scuola' },
    { word: 'QUADERNO', categoria: 'Scuola' },
    { word: 'PAGINA', categoria: 'Scuola' },
    { word: 'RICREAZIONE', categoria: 'Scuola' },
    { word: 'AULA', categoria: 'Scuola' },
    { word: 'SCIENZE', categoria: 'Scuola' },
    { word: 'MATEMATICA', categoria: 'Scuola' },
    { word: 'ITALIANO', categoria: 'Scuola' },
    { word: 'GEOGRAFIA', categoria: 'Scuola' },
    { word: 'FISICA', categoria: 'Scuola' },
    { word: 'CHIMICA', categoria: 'Scuola' },
    { word: 'CARTELLA', categoria: 'Scuola' },
    { word: 'ASTUCCIO', categoria: 'Scuola' },
    { word: 'TEMPERINO', categoria: 'Scuola' },
    { word: 'FORBICI', categoria: 'Scuola' },
    { word: 'PENNELLO', categoria: 'Scuola' },
    { word: 'ALUNNO', categoria: 'Scuola' },
    { word: 'LEZIONE', categoria: 'Scuola' },
    { word: 'RIPETIZIONE', categoria: 'Scuola' },

    // ── Città (nuova) ────────────────────────────────────────────────────
    { word: 'ROMA', categoria: 'Città' },
    { word: 'MILANO', categoria: 'Città' },
    { word: 'NAPOLI', categoria: 'Città' },
    { word: 'TORINO', categoria: 'Città' },
    { word: 'FIRENZE', categoria: 'Città' },
    { word: 'VENEZIA', categoria: 'Città' },
    { word: 'BOLOGNA', categoria: 'Città' },
    { word: 'PALERMO', categoria: 'Città' },
    { word: 'GENOVA', categoria: 'Città' },
    { word: 'BARI', categoria: 'Città' },
    { word: 'VERONA', categoria: 'Città' },
    { word: 'TRIESTE', categoria: 'Città' },
    { word: 'PARMA', categoria: 'Città' },
    { word: 'MODENA', categoria: 'Città' },
    { word: 'PISA', categoria: 'Città' },
    { word: 'SIENA', categoria: 'Città' },
    { word: 'RAVENNA', categoria: 'Città' },
    { word: 'LECCE', categoria: 'Città' },
    { word: 'CATANIA', categoria: 'Città' },
    { word: 'CAGLIARI', categoria: 'Città' },
    { word: 'PERUGIA', categoria: 'Città' },
    { word: 'UDINE', categoria: 'Città' },
    { word: 'BRESCIA', categoria: 'Città' },
    { word: 'BERGAMO', categoria: 'Città' },
    { word: 'PADOVA', categoria: 'Città' },
    { word: 'VICENZA', categoria: 'Città' },
    { word: 'REGGIO', categoria: 'Città' },
    { word: 'PESCARA', categoria: 'Città' },
    { word: 'ANCONA', categoria: 'Città' },
    { word: 'TARANTO', categoria: 'Città' },
    { word: 'MESSINA', categoria: 'Città' },
    { word: 'SALERNO', categoria: 'Città' },
    { word: 'PRATO', categoria: 'Città' },
    { word: 'LIVORNO', categoria: 'Città' },
    { word: 'AREZZO', categoria: 'Città' },
    { word: 'TREVISO', categoria: 'Città' },
    { word: 'GROSSETO', categoria: 'Città' },
    { word: 'LATINA', categoria: 'Città' },
    { word: 'FOGGIA', categoria: 'Città' },
    { word: 'COSENZA', categoria: 'Città' },
    { word: 'AGRIGENTO', categoria: 'Città' },
    { word: 'SIRACUSA', categoria: 'Città' },
    { word: 'TRAPANI', categoria: 'Città' },
    { word: 'ORISTANO', categoria: 'Città' },
    { word: 'NUORO', categoria: 'Città' },
    { word: 'MATERA', categoria: 'Città' },
    { word: 'FROSINONE', categoria: 'Città' },
    { word: 'SONDRIO', categoria: 'Città' },
    { word: 'NOVARA', categoria: 'Città' },
    { word: 'VARESE', categoria: 'Città' },
    { word: 'COMO', categoria: 'Città' },
    { word: 'MANTOVA', categoria: 'Città' },
    { word: 'CREMONA', categoria: 'Città' },
    { word: 'LODI', categoria: 'Città' },
    { word: 'PIACENZA', categoria: 'Città' },
    { word: 'FERRARA', categoria: 'Città' },
    { word: 'FORLI', categoria: 'Città' },
    { word: 'PESARO', categoria: 'Città' },
    { word: 'MACERATA', categoria: 'Città' },
    { word: 'ASCOLI', categoria: 'Città' },
    { word: 'TERNI', categoria: 'Città' },
    { word: 'RIMINI', categoria: 'Città' },
    { word: 'CESENA', categoria: 'Città' },

    // ── Anime e Cartoni (nuova) ──────────────────────────────────────────
    { word: 'NARUTO', categoria: 'Anime e Cartoni' },
    { word: 'ONEPIECE', categoria: 'Anime e Cartoni' },
    { word: 'DRAGONBALL', categoria: 'Anime e Cartoni' },
    { word: 'DORAEMON', categoria: 'Anime e Cartoni' },
    { word: 'SPONGEBOB', categoria: 'Anime e Cartoni' },
    { word: 'SNOOPY', categoria: 'Anime e Cartoni' },
    { word: 'GARFIELD', categoria: 'Anime e Cartoni' },
    { word: 'TOMJERRY', categoria: 'Anime e Cartoni' },
    { word: 'SCOOBYDOO', categoria: 'Anime e Cartoni' },
    { word: 'BLUEY', categoria: 'Anime e Cartoni' },
    { word: 'SHINOBI', categoria: 'Anime e Cartoni' },
    { word: 'SAMURAI', categoria: 'Anime e Cartoni' },
    { word: 'ANIME', categoria: 'Anime e Cartoni' },
    { word: 'MANGA', categoria: 'Anime e Cartoni' },
    { word: 'OTAKU', categoria: 'Anime e Cartoni' },
    { word: 'COSPLAY', categoria: 'Anime e Cartoni' },
    { word: 'FIGURINA', categoria: 'Anime e Cartoni' },
    { word: 'CHIBI', categoria: 'Anime e Cartoni' },
    { word: 'KAWAII', categoria: 'Anime e Cartoni' },
    { word: 'SENPAI', categoria: 'Anime e Cartoni' },
    { word: 'NINJA', categoria: 'Anime e Cartoni' },

    // ── Film e Serie (nuova) ─────────────────────────────────────────────
    { word: 'AVATAR', categoria: 'Film e Serie' },
    { word: 'JOKER', categoria: 'Film e Serie' },
    { word: 'THANOS', categoria: 'Film e Serie' },
    { word: 'DEADPOOL', categoria: 'Film e Serie' },
    { word: 'WOLVERINE', categoria: 'Film e Serie' },
    { word: 'VENOM', categoria: 'Film e Serie' },
    { word: 'TERMINATOR', categoria: 'Film e Serie' },
    { word: 'PREDATOR', categoria: 'Film e Serie' },
    { word: 'ALIEN', categoria: 'Film e Serie' },
    { word: 'MATRIX', categoria: 'Film e Serie' },
    { word: 'TRON', categoria: 'Film e Serie' },
    { word: 'FRANKENSTEIN', categoria: 'Film e Serie' },
    { word: 'DRACULA', categoria: 'Film e Serie' },
    { word: 'WOLFMAN', categoria: 'Film e Serie' },
    { word: 'FRIENDS', categoria: 'Film e Serie' },
    { word: 'SIMPSONS', categoria: 'Film e Serie' },
    { word: 'HOMER', categoria: 'Film e Serie' },
    { word: 'MARGE', categoria: 'Film e Serie' },
    { word: 'BART', categoria: 'Film e Serie' },
    { word: 'LISA', categoria: 'Film e Serie' },
    { word: 'KRUSTY', categoria: 'Film e Serie' },
    { word: 'GHOSTBUSTERS', categoria: 'Film e Serie' },
    { word: 'GREMLINS', categoria: 'Film e Serie' },
    { word: 'ROCKY', categoria: 'Film e Serie' },
    { word: 'RAMBO', categoria: 'Film e Serie' },
    { word: 'GODZILLA', categoria: 'Film e Serie' },
    { word: 'KINGKONG', categoria: 'Film e Serie' },
    { word: 'TITANIC', categoria: 'Film e Serie' },
    { word: 'INCEPTION', categoria: 'Film e Serie' },
    { word: 'GLADIATOR', categoria: 'Film e Serie' },
    { word: 'TROY', categoria: 'Film e Serie' },
    { word: 'HARRYPOTTER', categoria: 'Film e Serie' },
    { word: 'GANDALF', categoria: 'Film e Serie' },
    { word: 'FRODO', categoria: 'Film e Serie' },
    { word: 'ARAGORN', categoria: 'Film e Serie' },
    { word: 'LEGOLAS', categoria: 'Film e Serie' },
    { word: 'BILBO', categoria: 'Film e Serie' },
    { word: 'SAURON', categoria: 'Film e Serie' },
    { word: 'GOLUM', categoria: 'Film e Serie' },
    { word: 'VOLDEMORT', categoria: 'Film e Serie' },
    { word: 'HAGRID', categoria: 'Film e Serie' },
    { word: 'DRACO', categoria: 'Film e Serie' },
    { word: 'SNAPE', categoria: 'Film e Serie' },
    { word: 'LUPIN', categoria: 'Film e Serie' },
];

// Normalizza una parola per confronti: MAIUSCOLO, niente spazi/segni.
const norm = (w) => String(w || '').toUpperCase().replace(/[^A-Z]/g, '');

// Sotto-archivio utile per il Wordle: solo parole di 5 lettere "pulite"
// (5 caratteri MAIUSCOLI senza accenti), senza duplicati. Così la parola
// mostrata e quella da digitare coincidono sempre.
const WORDLE_POOL = Array.from(
    new Map(WORD_BANK
        .filter((w) => /^[A-Z]{5}$/.test(w.word))
        .map((w) => [w.word, w]))
        .values()
);

// Filtra per lunghezza (in lettere normalizzate), es. { minLen, maxLen }.
const filterByLen = (minLen, maxLen) =>
    WORD_BANK.filter((w) => {
        const len = norm(w.word).length;
        return len >= minLen && len <= maxLen;
    });

// Seleziona una parola escludendo quelle già usate, così niente ripetizioni
// finché non si esaurisce l'archivio (poi riparte).
// Ritorna { word, categoria, used } dove `used` è il nuovo elenco aggiornato.
const pickWord = ({ minLen = 1, maxLen = 99, exclude = [], random = Math.random } = {}) => {
    const pool = filterByLen(minLen, maxLen);
    const fresh = pool.filter((w) => !exclude.includes(norm(w.word)));
    const candidates = fresh.length ? fresh : pool;
    const entry = candidates[Math.floor(random() * candidates.length)];
    const word = norm(entry.word);
    return { word, categoria: entry.categoria, used: [...exclude, word] };
};

module.exports = {
    WORD_BANK,
    WORDLE_POOL,
    norm,
    filterByLen,
    pickWord,
};